name: Deploy to S3

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.FROSTOR_IO_DEPLOYER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.FROSTOR_IO_DEPLOYER_SECRET_KEY }}
          aws-region: us-east-2

      - name: Install Dependencies
        run: npm i

      - name: Build Static WebApp
        run: npm run generate

      - name: Deploy to S3
        run: aws s3 sync .output/public s3://frostor.io --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.FROSTOR_CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"
